### ISSUE TITLE
Can't get it to work.. skipsolabs -css files not available.. 

### ISSUE THREAD

**Issue by k2OS** [SkipsoLabs/collapsible#10]
I can't get it to work.. after fixing to minor errors in the demo-index.html, I am getting the menu twice, with the burger logo inbetween and 2x 404 errors to bootstrap and core.css..

**Comment by sav-valerio** [comment]
Sorry for the late reply, but this project is not maintained anymore.

Please feel free to create a fork if you need it.
Thanks!
